<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x64</PlatformTarget>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Helmert2D.Core\Helmert2D.Core.csproj">
		  <Private>True</Private>
		</ProjectReference>

		<Reference Include="AcCoreMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\AcCoreMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AcDbMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\AcDbMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AcMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\AcMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>

		<Reference Include="AecBaseMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\ACA\AecBaseMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AeccDbMgdge">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\C3D\AeccDbMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="CivilMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\C3D\CivilMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="CivilDbMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2025\C3D\CivilDbMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>